oauth:
  client-id: client
  client-secret: password
  url: "http://127.0.0.1:8081/oauth/token"
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codelab_db?serverTimezone=UTC&useSSL=false
    username: codelab
    password: codelab
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.hbm2ddl.auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
